### PR TITLE
Split versions into directories, added preface to LaTeX

### PR DESCRIPTION
**Pull request by khoover**
Started making the LaTeX version, copied and pasted the preface from the google doc in.

### CODE REVIEW

**Comment by sejoplejo** [comment]
Is this still being worked on? Judging by your comment on discord, I'm not sure if you only stopped working on a conversion script, or the LaTeX project as a whole.

**Comment by khoover** [comment]
Yeah, it's just the script I'm not working on.

**Comment by sejoplejo** [comment]
How long do you reckon it will take? Like, I can appreciate a clean source (in comparison to just the copied reddit posts) but I'm not sure if it's worth it to convert it manually. Also, all changes would have to be done twice to keep both the HTML and LaTeX versions synced.

**Comment by khoover** [comment]
It's probably going to take a week or so, with my schedule. But that's a fair point.

**Comment by sejoplejo** [comment]
So what do you reckon? Should we abort this project?

**Comment by khoover** [comment]
Maybe. But it really does look like a legitimate textbook with the LaTeX, maybe even moreso if I replaced the footnote links with proper citations.

**Comment by sejoplejo** [comment]
I agree it has more of a professional look and feel. Look, I'll make a strawpoll and post it in the discord. If people want it to be in Latex, the effort might be worth it.

**Pull request merged**
